name: Publish NPM Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: sample-packages/npm

      - uses: actions/setup-node@v3
        with:
          node-version: 12

      - run: |
          npm ci
          npm test

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: sample-packages/npm

      - uses: actions/setup-node@v3
        with:
          node-version: 12
   
